# Unused but required. Matches repository's name.
title: jkgh20.github.io

name: John Kim

# Removing or omitting this says: "No GitHub API authentication could be found."
description: Unused

avatar: /images/about-avatar.png

url:

baseurl:

permalink: /:title/

paginate: 10
paginate_path: /page:num/

excerpt_separator: <!--more-->

navigation:
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

footer-links:
  behance:
  dribbble:
  email: jkj7420@gmail.com
  facebook:
  flickr:
  github: jkgh20
  googleplus:
  instagram:
  linkedin: john-kim-58553689
  pinterest:
  rss:
  stackoverflow:
  tumblr:
  twitter:
  youtube: channel/UC9w5jAYW6wfSybRKq9X26kw

footer-text: © 2020 John Kim
